#!/usr/bin/env python3
"""gen_second_opinion.py — regenerate the second-opinion skill copies
(one per harness, named in HARNESS_TABLE) from one canonical template.

The second-opinion contract used to live in hand-maintained copies, one per
harness (claude/commands/second-opinion.md plus a sibling skill/command
form for each of opencode, copilot, agy, and pi). They drifted repeatedly,
and each drift caused a real bug (see `test/test_second_opinion_docs.py`'s
docstring). This script replaces those copies with one generated output: a
shared body template (`templates/second_opinion.md.tmpl`) plus a small
per-harness parameter table below, mirroring `gen_interfaces.py`'s
generator/--check/--stdout shape.

This does not close every drift class. A second, distinct failure mode is
the copies (or now, the one template) going stale relative to the actual
backing script (`second_opinion.py`) they describe — the `--model-index`
bug was exactly this: the flag already existed everywhere, only its real
behavior changed, and no doc followed. `--check` also runs a narrow guard
against that: a contract-shape check (every flag/subcommand
`INTERFACES.md` lists for `second_opinion.py`'s `review`/`detect`
subcommands is named somewhere in the template) and a guard-phrase check
(a short, hand-maintained list of exact substrings that must appear in both
`INTERFACES.md`'s help text and the template, for flags where the template
makes a specific behavioral claim). Both are doc-of-doc checks: they prove
the template still agrees with `INTERFACES.md`, not that `INTERFACES.md`
itself was kept accurate when the script's real behavior last changed.

The generator is pure and deterministic: no subprocesses, no network, no
writes to `~/.claude` — only reading the template + `INTERFACES.md` and
writing the repo files named in HARNESS_TABLE (skipped in
`--check`/`--stdout`).

Usage:
    python3 claude/scripts/gen_second_opinion.py            rewrite every copy
    python3 claude/scripts/gen_second_opinion.py --check     exit 1 if any copy,
                                                              the contract shape, or
                                                              a guard phrase is stale
    python3 claude/scripts/gen_second_opinion.py --stdout    print the rendered
                                                              copies, write nothing

Flags: --check, --stdout, --repo-root <path>, --quiet/-q, --verbose/-v.
Env vars: none.
Files read: <repo>/templates/second_opinion.md.tmpl, <repo>/INTERFACES.md.
Files written: the copies named in HARNESS_TABLE (skipped by --check
and --stdout).
Exit codes: 0 success; 1 --check found drift (sibling, contract-shape, or
guard-phrase); 2 bad usage.

Requires Python 3.12+.
"""

import argparse
import ast
import difflib
import re
import sys
import textwrap
import tokenize
from dataclasses import dataclass
from pathlib import Path

import cli_common

TEMPLATE_PATH = "templates/second_opinion.md.tmpl"
INTERFACES_PATH = "INTERFACES.md"
SCRIPT_RELPATH = "claude/scripts/gen_second_opinion.py"
WRAP_WIDTH = 79

# A line that is nothing but one `{{TOKEN}}` -- see render_body.
WHOLE_LINE_PLACEHOLDER = re.compile(r"\{\{[A-Z_]+\}\}")

DO_NOT_EDIT_MARKER = """\
<!-- generated by claude/scripts/gen_second_opinion.py — do not edit;
edit the body template for shared wording or the per-harness parameter table
for harness-specific wording, then regenerate -->"""

# Flags/subcommands second-opinion.md's body must name somewhere, taken from
# INTERFACES.md's `review`/`detect` subcommand entries for second_opinion.py
# (not its top-level --quiet/-q / --verbose/-v, which are cli_common
# plumbing common to every script in this repo and were never part of any
# skill doc's documented usage).
CONTRACT_TOKENS = ("detect", "review", "--backend", "--focus-file", "--model-index")

# A short, hand-maintained list of exact substrings that must appear in both
# INTERFACES.md's help text for the named flag and the template — see the
# module docstring. Only flags where the template makes a specific
# behavioral claim get an entry; a flag mentioned only by name has nothing
# to guard. Each value must currently be an exact substring of both files —
# --check fails loudly (with the two texts) if it drifts out of either.
GUARD_PHRASES: dict[str, str] = {
    "--model-index": "pool is unset/empty or the index is out of range",
}


@dataclass(frozen=True)
class HarnessParams:
    """One harness's frontmatter block plus its body placeholder values."""

    frontmatter: str
    backends_never: str
    backends_none: str
    target_source_opening: str
    target_source_echo: str
    ask_choose_overwrite: str
    ask_choose_cap: str
    instructions_ref: str
    adversary_ref: str
    io_entrypoint: str
    usage_block: str
    review_call: str
    review_call_retry: str


HARNESS_TABLE: dict[str, HarnessParams] = {
    "claude/commands/second-opinion.md": HarnessParams(
        frontmatter="""\
---
name: second-opinion
description: Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model.
argument-hint: [plan file or text]
allowed-tools: [Read, Write, AskUserQuestion, "Bash(python3 ~/.claude/scripts/second_opinion.py:*)", "Bash(python3 ~/.claude/scripts/grill.py:*)"]
---
""",
        # claude reads $ARGUMENTS directly, the harness's own invocation
        # convention (checked against claude/commands/*.md's own house
        # style, 2026-08-19)
        backends_never="`agy`/`opencode`/`pi`/`copilot`",
        # claude can shell to all four backends, so "no backend available"
        # names all four (checked against llm_backends.py, 2026-08-30 —
        # pi joined the list alongside opencode, not in place of it)
        backends_none="none of `agy`, `opencode`, `pi`, or `copilot`",
        # claude reads $ARGUMENTS directly (checked against
        # claude/commands/*.md's own house style, 2026-08-19)
        target_source_opening=(
            "If `$ARGUMENTS` is non-empty, treat it as an explicit file path "
            "or inline plan text."
        ),
        # echoes the same $ARGUMENTS convention as the opening sentence
        # above, 2026-08-19
        target_source_echo="inline `$ARGUMENTS` text",
        # claude Code's structured multi-choice UI is AskUserQuestion (see
        # CLAUDE.md's Judgment calls section), 2026-08-19
        ask_choose_overwrite=(
            "apply CLAUDE.md's convention for asking the user to choose: "
            "`Yes, overwrite (recommended)` / `No, leave as-is`"
        ),
        # same AskUserQuestion convention as the overwrite choice above,
        # 2026-08-19
        ask_choose_cap=(
            "apply CLAUDE.md's convention for asking the user to choose: "
            "`Keep Claude's approach (recommended)` / "
            "`Use the reviewer's suggestion` / `Let me decide manually`"
        ),
        # claude's own shared instructions file is CLAUDE.md, 2026-08-19
        instructions_ref="CLAUDE.md's",
        # claude is naming a *different* harness's agent, so "opencode's"
        # reads naturally here — the other four harnesses never name
        # themselves, 2026-08-19
        adversary_ref="opencode's",
        # every harness but Pi shells out to the script itself,
        # 2026-08-30
        io_entrypoint="`python3 ~/.claude/scripts/second_opinion.py`",
        # every harness but Pi invokes the script through bash, so the
        # usage block stays a runnable command block, 2026-08-30
        usage_block="""\
```
second_opinion.py detect                        # which backends are present (JSON)
second_opinion.py review <plan-file-or-text> \\
    [--focus-file <path>] \\
    [--model-index N]                            # one critique from the
                                                  # priority-selected backend,
                                                  # optionally scoped with
                                                  # plan-specific risk hints
```\
""",
        # the loop's per-round call, matching the bash usage block above,
        # 2026-08-30
        review_call="""\
    critique = second_opinion.py review <current_plan> \\
                   [--focus-file <focus-hints-path>] \\
                   --model-index <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion.py review <current_plan> \\
                       [--focus-file <focus-hints-path>]   # retry, no index —\
""",
    ),
    "opencode/command/second-opinion.md": HarnessParams(
        frontmatter="""\
---
description: "Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model."
---
""",
        # opencode's user-typed command form also reads $ARGUMENTS, per
        # opencode's own command-file docs (2026-08-19)
        backends_never="`agy`/`opencode`/`pi`/`copilot`",
        # opencode can shell to all four backends, 2026-08-30 (pi added
        # alongside opencode, not in place of it)
        backends_none="none of `agy`, `opencode`, `pi`, or `copilot`",
        # the user-typed command form reads $ARGUMENTS, same as claude's,
        # per opencode's own command-file docs (2026-08-19)
        target_source_opening=(
            "If `$ARGUMENTS` is non-empty, treat it as an explicit file path "
            "or inline plan text."
        ),
        # echoes the same $ARGUMENTS convention as the opening sentence
        # above, 2026-08-19
        target_source_echo="inline `$ARGUMENTS` text",
        # opencode's structured multi-choice UI is its `question` tool, per
        # opencode's own docs (2026-08-19)
        ask_choose_overwrite=(
            "`question` tool: `Yes, overwrite (recommended)` / `No, leave as-is`"
        ),
        # same `question` tool convention as the overwrite choice above,
        # 2026-08-19
        ask_choose_cap=(
            "`question` tool: `Keep the current approach (recommended)` / "
            "`Use the reviewer's suggestion` / `Let me decide manually`"
        ),
        # opencode has no single shared-instructions filename of its own
        # (no CLAUDE.md equivalent), so it names the concept generically,
        # 2026-08-19
        instructions_ref="the shared instructions file's",
        # opencode is naming its own `adversary` agent, so it stays
        # unnamed ("the"), matching the other non-claude harnesses,
        # 2026-08-19
        adversary_ref="the",
        # every harness but Pi shells out to the script itself,
        # 2026-08-30
        io_entrypoint="`python3 ~/.claude/scripts/second_opinion.py`",
        # every harness but Pi invokes the script through bash, so the
        # usage block stays a runnable command block, 2026-08-30
        usage_block="""\
```
second_opinion.py detect                        # which backends are present (JSON)
second_opinion.py review <plan-file-or-text> \\
    [--focus-file <path>] \\
    [--model-index N]                            # one critique from the
                                                  # priority-selected backend,
                                                  # optionally scoped with
                                                  # plan-specific risk hints
```\
""",
        # the loop's per-round call, matching the bash usage block above,
        # 2026-08-30
        review_call="""\
    critique = second_opinion.py review <current_plan> \\
                   [--focus-file <focus-hints-path>] \\
                   --model-index <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion.py review <current_plan> \\
                       [--focus-file <focus-hints-path>]   # retry, no index —\
""",
    ),
    "opencode/skills/second-opinion/SKILL.md": HarnessParams(
        frontmatter="""\
---
name: second-opinion
description: Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model.
---
""",
        # opencode can shell to all four backends regardless of
        # invocation layer, 2026-08-30 (pi added alongside opencode)
        backends_never="`agy`/`opencode`/`pi`/`copilot`",
        # opencode can shell to all four backends, 2026-08-30
        backends_none="none of `agy`, `opencode`, `pi`, or `copilot`",
        # the model-invoked skill form has no $ARGUMENTS; it only sees the
        # invoking message, per opencode's own skill-invocation docs
        # (2026-08-19)
        target_source_opening=(
            "If the invoking message names an explicit file path or inline "
            "plan text (e.g. another command or skill delegated to you with "
            "a specific plan), treat it as the target."
        ),
        # echoes the same invoking-message convention as the opening
        # sentence above, 2026-08-19
        target_source_echo="inline text from the invoking message",
        # opencode's structured multi-choice UI is its `question` tool,
        # same as the command form, 2026-08-19
        ask_choose_overwrite=(
            "`question` tool: `Yes, overwrite (recommended)` / `No, leave as-is`"
        ),
        # same `question` tool convention as the overwrite choice above,
        # 2026-08-19
        ask_choose_cap=(
            "`question` tool: `Keep the current approach (recommended)` / "
            "`Use the reviewer's suggestion` / `Let me decide manually`"
        ),
        # opencode has no CLAUDE.md equivalent, 2026-08-19
        instructions_ref="the shared instructions file's",
        # opencode is naming its own `adversary` agent, stays unnamed,
        # 2026-08-19
        adversary_ref="the",
        # every harness but Pi shells out to the script itself,
        # 2026-08-30
        io_entrypoint="`python3 ~/.claude/scripts/second_opinion.py`",
        # every harness but Pi invokes the script through bash, so the
        # usage block stays a runnable command block, 2026-08-30
        usage_block="""\
```
second_opinion.py detect                        # which backends are present (JSON)
second_opinion.py review <plan-file-or-text> \\
    [--focus-file <path>] \\
    [--model-index N]                            # one critique from the
                                                  # priority-selected backend,
                                                  # optionally scoped with
                                                  # plan-specific risk hints
```\
""",
        # the loop's per-round call, matching the bash usage block above,
        # 2026-08-30
        review_call="""\
    critique = second_opinion.py review <current_plan> \\
                   [--focus-file <focus-hints-path>] \\
                   --model-index <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion.py review <current_plan> \\
                       [--focus-file <focus-hints-path>]   # retry, no index —\
""",
    ),
    "copilot/skills/second-opinion/SKILL.md": HarnessParams(
        frontmatter="""\
---
name: second-opinion
description: Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model.
allowed-tools: shell
---
""",
        # copilot cannot shell to a sibling harness's CLI directly; the
        # skill still names all four since copilot itself can be the
        # backend (unlike agy, which never can), per copilot skills docs
        # (2026-08-19; pi added 2026-08-30 alongside opencode)
        backends_never="`agy`/`opencode`/`pi`/`copilot`",
        # copilot can be a backend for the other three harnesses even
        # though it can't shell out itself, so "no backend available"
        # still names all four, 2026-08-30
        backends_none="none of `agy`, `opencode`, `pi`, or `copilot`",
        # copilot CLI has no $ARGUMENTS equivalent; it only sees what the
        # user typed or pasted, per copilot skills docs (2026-08-19)
        target_source_opening=(
            "If the user named a specific file path or pasted plan text, "
            "treat that as the target."
        ),
        # echoes the same user-typed/pasted convention as the opening
        # sentence above, 2026-08-19
        target_source_echo="pasted text",
        # copilot CLI has no structured multi-choice widget; plain text per
        # the shared instructions file's harnesses-without-a-widget
        # convention (2026-08-19)
        ask_choose_overwrite=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: overwrite (recommended) or leave as-is"
        ),
        # same plain-text convention as the overwrite choice above,
        # 2026-08-19
        ask_choose_cap=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: keep your approach (recommended), use the "
            "reviewer's suggestion, or let the user decide manually"
        ),
        # copilot has no CLAUDE.md equivalent, 2026-08-19
        instructions_ref="the shared instructions file's",
        # copilot is naming opencode's `adversary` agent but, like the
        # other three non-claude harnesses, leaves it unnamed rather than
        # calling out "opencode's" specifically — settled wording, not
        # something this item's plan changes, 2026-08-19
        adversary_ref="the",
        # every harness but Pi shells out to the script itself,
        # 2026-08-30
        io_entrypoint="`python3 ~/.claude/scripts/second_opinion.py`",
        # every harness but Pi invokes the script through bash, so the
        # usage block stays a runnable command block, 2026-08-30
        usage_block="""\
```
second_opinion.py detect                        # which backends are present (JSON)
second_opinion.py review <plan-file-or-text> \\
    [--focus-file <path>] \\
    [--model-index N]                            # one critique from the
                                                  # priority-selected backend,
                                                  # optionally scoped with
                                                  # plan-specific risk hints
```\
""",
        # the loop's per-round call, matching the bash usage block above,
        # 2026-08-30
        review_call="""\
    critique = second_opinion.py review <current_plan> \\
                   [--focus-file <focus-hints-path>] \\
                   --model-index <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion.py review <current_plan> \\
                       [--focus-file <focus-hints-path>]   # retry, no index —\
""",
    ),
    "agy/skills/second-opinion/SKILL.md": HarnessParams(
        frontmatter="""\
---
name: second-opinion
description: Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model.
---
""",
        # agy can shell to agy/opencode/pi only — it cannot reach copilot,
        # per agy's own backshelling docs (2026-08-19; pi added 2026-08-30
        # as the same class of CLI tool as opencode)
        backends_never="`agy`/`opencode`/`pi`",
        # agy can only ever see agy, opencode, or pi as a backend, so "no
        # backend available" names those three, 2026-08-30
        backends_none="none of `agy`, `opencode`, or `pi`",
        # agy CLI has no $ARGUMENTS equivalent; it only sees what the user
        # typed or pasted, per agy's own skills docs (2026-08-19)
        target_source_opening=(
            "If the user named a specific file path or pasted plan text, "
            "treat that as the target."
        ),
        # echoes the same user-typed/pasted convention as the opening
        # sentence above, 2026-08-19
        target_source_echo="pasted text",
        # agy CLI has no structured multi-choice widget; plain text per
        # the shared instructions file's harnesses-without-a-widget
        # convention, same as copilot (2026-08-19)
        ask_choose_overwrite=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: overwrite (recommended) or leave as-is"
        ),
        # same plain-text convention as the overwrite choice above,
        # 2026-08-19
        ask_choose_cap=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: keep your approach (recommended), use the "
            "reviewer's suggestion, or let the user decide manually"
        ),
        # agy has no CLAUDE.md equivalent, 2026-08-19
        instructions_ref="the shared instructions file's",
        # agy is naming opencode's `adversary` agent but leaves it
        # unnamed, same as copilot, 2026-08-19
        adversary_ref="the",
        # every harness but Pi shells out to the script itself,
        # 2026-08-30
        io_entrypoint="`python3 ~/.claude/scripts/second_opinion.py`",
        # every harness but Pi invokes the script through bash, so the
        # usage block stays a runnable command block, 2026-08-30
        usage_block="""\
```
second_opinion.py detect                        # which backends are present (JSON)
second_opinion.py review <plan-file-or-text> \\
    [--focus-file <path>] \\
    [--model-index N]                            # one critique from the
                                                  # priority-selected backend,
                                                  # optionally scoped with
                                                  # plan-specific risk hints
```\
""",
        # the loop's per-round call, matching the bash usage block above,
        # 2026-08-30
        review_call="""\
    critique = second_opinion.py review <current_plan> \\
                   [--focus-file <focus-hints-path>] \\
                   --model-index <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion.py review <current_plan> \\
                       [--focus-file <focus-hints-path>]   # retry, no index —\
""",
    ),
    "pi/prompts/second-opinion.md": HarnessParams(
        frontmatter="""\
---
description: "Send a plan to a non-Claude model for adversarial critique, then iterate — revise, re-send, repeat — until the critique stops surfacing anything new or a round cap is hit. Use when the user wants a second opinion, an outside critique, or to stress-test a plan against a different model."
argument-hint: [plan file or text]
---
""",
        # Pi's user-typed prompt-template form reads $ARGUMENTS with the
        # same placeholder syntax as opencode's command form (verified live
        # against a real Pi install, 2026-08-30) and, like opencode, has no
        # restriction on which backend CLIs it can shell out to
        backends_never="`agy`/`opencode`/`pi`/`copilot`",
        # same reasoning as opencode's rows above, 2026-08-30
        backends_none="none of `agy`, `opencode`, `pi`, or `copilot`",
        # Pi's prompt-template form reads $ARGUMENTS, same as opencode's
        # command form, 2026-08-30
        target_source_opening=(
            "If `$ARGUMENTS` is non-empty, treat it as an explicit file path "
            "or inline plan text."
        ),
        # echoes the same $ARGUMENTS convention as the opening sentence
        # above, 2026-08-30
        target_source_echo="inline `$ARGUMENTS` text",
        # no structured multi-choice widget for Pi is confirmed from
        # research so far; plain text per the shared instructions file's
        # harnesses-without-a-widget convention, same as copilot/agy,
        # 2026-08-30
        ask_choose_overwrite=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: overwrite (recommended) or leave as-is"
        ),
        # same plain-text convention as the overwrite choice above,
        # 2026-08-30
        ask_choose_cap=(
            "apply the shared instructions file's convention for asking the "
            "user to choose: keep your approach (recommended), use the "
            "reviewer's suggestion, or let the user decide manually"
        ),
        # Pi has no CLAUDE.md equivalent of its own, 2026-08-30
        instructions_ref="the shared instructions file's",
        # Pi is naming opencode's `adversary` agent (Pi has no adversary-
        # agent equivalent of its own) but leaves it unnamed, same as
        # copilot/agy, 2026-08-30
        adversary_ref="the",
        # Pi routes backend I/O through its native second_opinion tool
        # (pi/extensions/second-opinion-tool.ts), 2026-08-30
        io_entrypoint="the `second_opinion` tool",
        # Pi calls the native second_opinion tool
        # (pi/extensions/second-opinion-tool.ts), so its usage block is
        # prose, deliberately with no code fence: pi-tool-dev-status showed
        # a fenced command block is read as an instruction to run bash no
        # matter what the surrounding prose says, 2026-08-30
        usage_block=(
            "Call the `second_opinion` tool. Action `detect` lists the "
            "available backends as JSON. Action `review` returns one "
            "critique of the plan at `planFile`, optionally scoped with "
            "`focusFile` and `modelIndex`. Never run `second_opinion.py` "
            "via bash."
        ),
        # the loop's per-round call, naming the tool and its parameter
        # names rather than the script and its CLI flags, 2026-08-30
        review_call="""\
    critique = second_opinion review
                   planFile = <current_plan>
                   [focusFile = <focus-hints-path>]
                   modelIndex = <round - 1>   # one call\
""",
        # the same call without the index, for the no-pool retry, 2026-08-30
        review_call_retry="""\
        critique = second_opinion review
                       planFile = <current_plan>
                       [focusFile = <focus-hints-path>]   # retry, no index —\
""",
    ),
}


# ── rendering ────────────────────────────────────────────────────────────────


def substitutions(params: HarnessParams) -> dict[str, str]:
    """Map each `{{TOKEN}}` in the template to this harness's value."""
    return {
        "BACKENDS_NEVER": params.backends_never,
        "BACKENDS_NONE": params.backends_none,
        "TARGET_SOURCE_OPENING": params.target_source_opening,
        "TARGET_SOURCE_ECHO": params.target_source_echo,
        "ASK_CHOOSE_OVERWRITE": params.ask_choose_overwrite,
        "ASK_CHOOSE_CAP": params.ask_choose_cap,
        "INSTRUCTIONS_REF": params.instructions_ref,
        "ADVERSARY_REF": params.adversary_ref,
        "IO_ENTRYPOINT": params.io_entrypoint,
        "USAGE_BLOCK": params.usage_block,
        "REVIEW_CALL": params.review_call,
        "REVIEW_CALL_RETRY": params.review_call_retry,
    }


def apply_placeholders(text: str, values: dict[str, str]) -> str:
    """Replace every `{{TOKEN}}` in ``text`` with its harness-specific value."""
    for token, value in values.items():
        text = text.replace("{{" + token + "}}", value)
    return text


def render_body(template_text: str, params: HarnessParams) -> str:
    """Render one harness's body: substitute placeholders, then reflow prose.

    Code fences (```...```) and blank lines pass through untouched. Every
    other block is one prose paragraph: substitute first (placeholder
    values differ in length per harness), then wrap at ``WRAP_WIDTH`` so the
    committed output stays readable regardless of which harness's value was
    substituted in.
    """
    values = substitutions(params)
    lines = template_text.splitlines()
    out: list[str] = []
    paragraph: list[str] = []
    in_fence = False

    def flush() -> None:
        if not paragraph:
            return
        text = apply_placeholders(" ".join(paragraph), values)
        if text.startswith("#"):
            out.append(text)
        else:
            out.append(
                textwrap.fill(
                    text,
                    width=WRAP_WIDTH,
                    break_long_words=False,
                    break_on_hyphens=False,
                )
            )
        paragraph.clear()

    for line in lines:
        if line.strip().startswith("```"):
            flush()
            out.append(line)
            in_fence = not in_fence
            continue
        if in_fence:
            # Fenced pseudocode still carries per-harness call forms; only
            # the reflow is skipped in here, not the substitution.
            out.append(apply_placeholders(line, values))
            continue
        if line.strip() == "":
            flush()
            out.append("")
            continue
        if WHOLE_LINE_PLACEHOLDER.fullmatch(line.strip()):
            # A whole-line placeholder is emitted verbatim rather than
            # reflowed, so its value can carry its own fence, indentation,
            # and line breaks -- that is what lets one harness render a
            # fenced command block here where another renders prose. Its
            # own ``` markers are deliberately not fed back into the fence
            # tracking above: the value is already final text, and toggling
            # on it would stop every later paragraph from being wrapped.
            flush()
            value = apply_placeholders(line.strip(), values)
            if "```" in value or "\n" in value:
                out.append(value)
            else:
                # A single-line prose value still reflows, so a harness
                # whose block is prose matches the wrapping of every other
                # paragraph around it.
                out.append(
                    textwrap.fill(
                        value,
                        width=WRAP_WIDTH,
                        break_long_words=False,
                        break_on_hyphens=False,
                    )
                )
            continue
        paragraph.append(line.strip())
    flush()
    return "\n".join(out).rstrip("\n") + "\n"


def render_file(template_text: str, relpath: str, params: HarnessParams) -> str:
    """Render one harness's complete file: frontmatter, marker, body."""
    body = render_body(template_text, params)
    return f"{params.frontmatter}\n{DO_NOT_EDIT_MARKER}\n\n{body}"


def render_all(repo_root: Path) -> dict[str, str]:
    """Render every harness's file, keyed by its repo-relative output path."""
    template_text = (repo_root / TEMPLATE_PATH).read_text(encoding="utf-8")
    return {
        relpath: render_file(template_text, relpath, params)
        for relpath, params in HARNESS_TABLE.items()
    }


# ── contract checks ─────────────────────────────────────────────────────────


def check_contract_shape(repo_root: Path, template_text: str) -> list[str]:
    """Return problems where a CONTRACT_TOKENS entry is missing from the template."""
    problems = []
    for token in CONTRACT_TOKENS:
        if token not in template_text:
            problems.append(
                f"contract-shape: {token!r} (from INTERFACES.md's "
                "second_opinion.py entry) is not named anywhere in "
                f"{TEMPLATE_PATH}"
            )
    return problems


def check_guard_phrases(repo_root: Path, template_text: str) -> list[str]:
    """Return problems where a guard phrase drifted out of either source."""
    interfaces_text = (repo_root / INTERFACES_PATH).read_text(encoding="utf-8")
    problems = []
    for flag, phrase in GUARD_PHRASES.items():
        if phrase not in interfaces_text:
            problems.append(
                f"guard-phrase: {flag!r}'s guard phrase {phrase!r} is no "
                f"longer a substring of {INTERFACES_PATH} — {flag}'s help "
                "text moved on; re-copy the phrase from its current help= "
                "string"
            )
        if phrase not in template_text:
            problems.append(
                f"guard-phrase: {flag!r}'s guard phrase {phrase!r} is no "
                f"longer a substring of {TEMPLATE_PATH} — the template's "
                f"claim about {flag} changed; update the phrase or the "
                "template text to match"
            )
    return problems


def check_row_comments(repo_root: Path) -> list[str]:
    """Return problems where a HARNESS_TABLE keyword argument has no comment
    on the line immediately above it.

    A presence check only (CLAUDE.md/plan §3): it proves a freshness note
    exists, not that the note's content is still accurate.
    """
    source_path = repo_root / SCRIPT_RELPATH
    source = source_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(source_path))

    comment_lines: set[int] = set()
    with open(source_path, "rb") as f:
        for tok in tokenize.tokenize(f.readline):
            if tok.type == tokenize.COMMENT:
                comment_lines.add(tok.start[0])

    problems = []
    table_assign = next(
        (
            node
            for node in tree.body
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "HARNESS_TABLE"
        ),
        None,
    )
    if table_assign is None or not isinstance(table_assign.value, ast.Dict):
        return [
            f"row-comments: HARNESS_TABLE not found as a dict literal in {SCRIPT_RELPATH}"
        ]

    for key_node, value_node in zip(
        table_assign.value.keys, table_assign.value.values, strict=True
    ):
        relpath = key_node.value if isinstance(key_node, ast.Constant) else "?"
        if not isinstance(value_node, ast.Call):
            continue
        for kw in value_node.keywords:
            if kw.arg is None:
                continue
            if kw.arg == "frontmatter":
                continue
            if (kw.lineno - 1) not in comment_lines:
                problems.append(
                    f"row-comments: {relpath}'s {kw.arg!r} row has no "
                    "freshness comment on the line above it"
                )
    return problems


# ── cli ──────────────────────────────────────────────────────────────────────


def default_repo_root() -> Path:
    """Return the repo root inferred from this script's real location."""
    return Path(__file__).resolve().parents[2]


def main() -> None:
    """Parse argv, then regenerate, check, or print the skill copies."""
    parser = argparse.ArgumentParser(
        prog="gen_second_opinion",
        description="regenerate the second-opinion skill copies from one template",
    )
    cli_common.add_verbosity_args(parser)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 (with diffs on stderr) if any copy, the contract shape, "
        "or a guard phrase is stale",
    )
    parser.add_argument(
        "--stdout", action="store_true", help="print the rendered copies, write nothing"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        metavar="<path>",
        help="repository root (default: inferred from this script's path)",
    )
    args = parser.parse_args()

    repo_root = (args.repo_root or default_repo_root()).resolve()
    template_file = repo_root / TEMPLATE_PATH
    if not template_file.is_file():
        print(
            f"[gen_second_opinion] no {TEMPLATE_PATH} under {repo_root}",
            file=sys.stderr,
        )
        sys.exit(2)

    rendered = render_all(repo_root)

    if args.stdout:
        for relpath, text in rendered.items():
            sys.stdout.write(f"# ── {relpath} ──\n{text}\n")
        return

    if args.check:
        template_text = template_file.read_text(encoding="utf-8")
        problems = [
            *check_contract_shape(repo_root, template_text),
            *check_guard_phrases(repo_root, template_text),
            *check_row_comments(repo_root),
        ]
        stale: list[str] = []
        for relpath, text in rendered.items():
            output = repo_root / relpath
            current = output.read_text(encoding="utf-8") if output.is_file() else ""
            if current != text:
                stale.append(relpath)
                diff = difflib.unified_diff(
                    current.splitlines(keepends=True),
                    text.splitlines(keepends=True),
                    fromfile=f"{relpath} (on disk)",
                    tofile=f"{relpath} (generated)",
                )
                sys.stderr.writelines(diff)
        if not problems and not stale:
            cli_common.qprint(
                f"[gen_second_opinion] all {len(rendered)} copies are up to date",
                quiet=args.quiet,
            )
            return
        for problem in problems:
            print(f"[gen_second_opinion] {problem}", file=sys.stderr)
        if stale:
            print(
                f"[gen_second_opinion] stale: {', '.join(stale)} — run "
                "`python3 claude/scripts/gen_second_opinion.py`",
                file=sys.stderr,
            )
        sys.exit(1)

    for relpath, text in rendered.items():
        (repo_root / relpath).write_text(text, encoding="utf-8")
    cli_common.qprint(
        f"[gen_second_opinion] wrote {len(rendered)} copies", quiet=args.quiet
    )


if __name__ == "__main__":
    main()
