#!/usr/bin/env python3
"""gen_core_instructions.py — compose CORE_INSTRUCTIONS.md + personal-overlay.md
into claude/global-instructions.md.

Dotfiles-only tool: agent-toolkit has no personal-overlay.md to compose
against and never runs this (see scripts/sync_from_dotfiles.py's EXCLUDE
entry for this script and personal-overlay.md) — it symlinks
claude/CORE_INSTRUCTIONS.md directly instead. This composes the two files
this user maintains here: the shareable core (synced into agent-toolkit)
and this machine's personal-policy overlay (never synced), joined with a
fixed append-at-end order and no markup in either input file, so
CORE_INSTRUCTIONS.md alone remains safe to symlink directly wherever it's
the only file loaded.

Usage:
    python3 claude/scripts/gen_core_instructions.py            write global-instructions.md
    python3 claude/scripts/gen_core_instructions.py --check     exit 1 if stale
    python3 claude/scripts/gen_core_instructions.py --stdout    print, write nothing

Flags: --check, --stdout, --repo-root <path>, --quiet/-q, --verbose/-v.
Env vars: none.
Files read: <repo>/claude/CORE_INSTRUCTIONS.md, <repo>/claude/personal-overlay.md.
Files written: <repo>/claude/global-instructions.md (skipped by --check and --stdout).
Exit codes: 0 success; 1 --check found stale output; 2 bad usage (missing input file).

Requires Python 3.12+.
"""

import argparse
import sys
from pathlib import Path

import cli_common

DO_NOT_EDIT_MARKER = (
    "<!-- generated by claude/scripts/gen_core_instructions.py — do not edit; "
    "edit claude/CORE_INSTRUCTIONS.md (shareable) or claude/personal-overlay.md "
    "(this machine's personal policy) instead, then regenerate -->"
)


def compose(repo_root: Path) -> str:
    """Read CORE_INSTRUCTIONS.md + personal-overlay.md, return the composed text.

    Fixed append-at-end order, no substitution markup in either input file:
    CORE_INSTRUCTIONS.md must remain valid, complete, self-contained
    instructions on its own, since agent-toolkit symlinks it directly with
    no generation step of its own.
    """
    core_path = repo_root / "claude" / "CORE_INSTRUCTIONS.md"
    overlay_path = repo_root / "claude" / "personal-overlay.md"
    for path in (core_path, overlay_path):
        if not path.is_file():
            print(f"[gen_core_instructions] missing {path}", file=sys.stderr)
            sys.exit(2)
    core_text = core_path.read_text(encoding="utf-8").rstrip("\n")
    overlay_text = overlay_path.read_text(encoding="utf-8").rstrip("\n")
    return f"{core_text}\n\n{DO_NOT_EDIT_MARKER}\n\n{overlay_text}\n"


def default_repo_root() -> Path:
    """Return the repo root inferred from this script's real location."""
    return Path(__file__).resolve().parents[2]


def main() -> None:
    """Parse argv, then compose, check, or print global-instructions.md."""
    parser = argparse.ArgumentParser(
        prog="gen_core_instructions",
        description="compose CORE_INSTRUCTIONS.md + personal-overlay.md into "
        "global-instructions.md",
    )
    cli_common.add_verbosity_args(parser)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 (with a diff-free notice on stderr) if the output is stale",
    )
    parser.add_argument(
        "--stdout", action="store_true", help="print the composed file, write nothing"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        metavar="<path>",
        help="repository root (default: inferred from this script's path)",
    )
    args = parser.parse_args()

    repo_root = (args.repo_root or default_repo_root()).resolve()
    composed = compose(repo_root)
    output_path = repo_root / "claude" / "global-instructions.md"

    if args.stdout:
        sys.stdout.write(composed)
        return

    if args.check:
        current = (
            output_path.read_text(encoding="utf-8") if output_path.is_file() else ""
        )
        if current == composed:
            cli_common.qprint(
                "[gen_core_instructions] global-instructions.md is up to date",
                quiet=args.quiet,
            )
            return
        print(
            "[gen_core_instructions] stale — run "
            "`python3 claude/scripts/gen_core_instructions.py`",
            file=sys.stderr,
        )
        sys.exit(1)

    output_path.write_text(composed, encoding="utf-8")
    cli_common.qprint(
        "[gen_core_instructions] wrote claude/global-instructions.md", quiet=args.quiet
    )


if __name__ == "__main__":
    main()
