#!/usr/bin/env python3
"""Tests for gen_skills.py. Run with: python3 test_gen_skills.py

Three kinds of coverage:
- `RenderBodyTests` — small unit tests for the substitution mechanism
  against a tiny fixture template (mirrors test_gen_second_opinion.py's
  RenderBodyTests).
- `CapabilityFixtureTests` — one fixture per (skill, harness) pair covered
  by `SKILL_HARNESSES` (20 for the 4 skills on all 5 harnesses, plus 9 for
  spec/standup/to-tickets on claude/opencode/pi only — 29 total), hand-written
  from each skill's real, already-verified per-harness facts (copilot/
  opencode/agy/pi's own CLAUDE_CODE_PARITY.md docs, or pi/prompts/*.md's
  already-verified Pi-specific wording for spec/standup/to-tickets), not
  generated by gen_skills.py itself — a fixture produced by the same table
  would be circular and would encode, not catch, a wrong table value. Each
  fixture asserts the small set of distinguishing substrings a swapped
  capability-table row would get wrong (structured-choice tool name,
  SessionStart-hook language, frontmatter shape, skill install path), not
  full-file equality — a wrong claude/agy swap on any of these is exactly
  the drift class that produced `meta-pi-skill-content-mismatch` in the
  first place.
- `EndToEndTests` — asserts the real templates + CAPABILITY_TABLE render
  to exactly the 29 files currently committed, so a forgotten regeneration
  fails the suite instead of drifting quietly.
"""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import gen_skills as gs
from gen_skills_params import SKILL_PARAMS

REPO_ROOT = Path(__file__).resolve().parents[2]


class RenderBodyTests(unittest.TestCase):
    def test_substitutes_inline_and_whole_line_placeholders(self) -> None:
        template = "prose {{A}} more prose.\n\n{{B}}\n\nafter.\n"
        values = {"A": "X", "B": "- item one\n- item two"}
        rendered = gs.render_body(template, values)
        self.assertNotIn("{{", rendered)
        self.assertIn("prose X more prose.", rendered)
        self.assertIn("- item one\n- item two", rendered)

    def test_does_not_reflow_numbered_lists_with_no_blank_lines(self) -> None:
        """The one reason this script's render_body deliberately skips
        gen_second_opinion.py's textwrap reflow: joining list items with no
        blank line between them into one paragraph would corrupt the list."""
        template = "1. First {{TOKEN}} item.\n2. Second item.\n3. Third item.\n"
        rendered = gs.render_body(template, {"TOKEN": "fixture"})
        self.assertIn("1. First fixture item.", rendered)
        self.assertIn("2. Second item.", rendered)
        self.assertIn("3. Third item.", rendered)

    def test_multiline_value_on_a_whole_line_placeholder(self) -> None:
        template = "before.\n\n{{BLOCK}}\n\nafter.\n"
        rendered = gs.render_body(template, {"BLOCK": "line one\nline two"})
        self.assertIn("before.\n\nline one\nline two\n\nafter.", rendered)


class CapabilityFixtureTests(unittest.TestCase):
    """One method per (skill, harness) pair — 20 total."""

    def _render(self, skill: str, harness: str) -> str:
        template_text = (REPO_ROOT / gs.TEMPLATE_PATHS[skill]).read_text(
            encoding="utf-8"
        )
        params = SKILL_PARAMS[skill][harness]
        return gs.render_one(skill, harness, template_text, params)

    # -- dashboard --------------------------------------------------------

    def test_dashboard_claude(self) -> None:
        text = self._render("dashboard", "claude")
        self.assertIn("name: dashboard", text)
        self.assertIn("SessionStart hook", text)
        self.assertIn("CLAUDE.md's Backlog section", text)

    def test_dashboard_copilot(self) -> None:
        text = self._render("dashboard", "copilot")
        self.assertIn("allowed-tools: shell", text)
        self.assertIn("sessionStart hook", text)
        self.assertIn("the shared instructions file's Backlog section", text)

    def test_dashboard_opencode(self) -> None:
        text = self._render("dashboard", "opencode")
        self.assertNotIn("\nname:", text.split("---", 2)[1])
        self.assertNotIn("SessionStart", text)
        self.assertIn("the shared instructions file's Backlog section", text)

    def test_dashboard_agy(self) -> None:
        text = self._render("dashboard", "agy")
        self.assertIn("name: dashboard", text)
        self.assertNotIn("SessionStart", text)
        self.assertIn("the shared instructions file's Backlog section", text)

    def test_dashboard_pi(self) -> None:
        text = self._render("dashboard", "pi")
        self.assertIn("name: dashboard", text)
        self.assertNotIn("SessionStart", text)
        self.assertIn("the shared instructions file's Backlog section", text)

    # -- grill-me -----------------------------------------------------------

    def test_grill_me_claude(self) -> None:
        text = self._render("grill-me", "claude")
        self.assertIn("AskUserQuestion", text)
        self.assertNotIn("the `question` tool", text)
        self.assertIn("SessionStart hook", text)

    def test_grill_me_copilot(self) -> None:
        text = self._render("grill-me", "copilot")
        self.assertNotIn("AskUserQuestion", text)
        self.assertNotIn("the `question` tool", text)
        self.assertIn("SessionStart hook", text)

    def test_grill_me_opencode(self) -> None:
        text = self._render("grill-me", "opencode")
        self.assertNotIn("AskUserQuestion", text)
        self.assertIn("the `question` tool", text)
        self.assertIn("opencode has no SessionStart hook", text)

    def test_grill_me_agy(self) -> None:
        text = self._render("grill-me", "agy")
        self.assertNotIn("AskUserQuestion", text)
        self.assertNotIn("the `question` tool", text)
        self.assertIn("agy has no `SessionStart`-equivalent hook event", text)

    def test_grill_me_pi(self) -> None:
        text = self._render("grill-me", "pi")
        self.assertNotIn("AskUserQuestion", text)
        self.assertIn("the `question` tool", text)
        # The bug this whole item exists to fix: Pi's copy used to be agy's,
        # claiming Pi has no structured-choice widget. It does (question-tool.ts).
        self.assertNotIn("no structured multi-choice widget", text)
        self.assertIn("session_start` extension event", text)

    # -- backlog-item ---------------------------------------------------

    def test_backlog_item_claude(self) -> None:
        text = self._render("backlog-item", "claude")
        self.assertIn("AskUserQuestion", text)
        self.assertIn("Cheaper Claude session", text)
        self.assertIn("opencode/GLM-5.2", text)

    def test_backlog_item_copilot(self) -> None:
        text = self._render("backlog-item", "copilot")
        self.assertIn("Cheaper Copilot session", text)
        self.assertIn("A cheaper Copilot model, same machine", text)
        self.assertNotIn("AskUserQuestion", text)

    def test_backlog_item_opencode(self) -> None:
        text = self._render("backlog-item", "opencode")
        self.assertIn("Fresh opencode session", text)
        self.assertIn("`question` tool", text)
        self.assertNotIn("AskUserQuestion", text)

    def test_backlog_item_agy(self) -> None:
        text = self._render("backlog-item", "agy")
        self.assertIn("Cheaper agy session", text)
        self.assertIn("suspend-and-return", text)
        self.assertIn("has no structured multi-choice widget", text)

    def test_backlog_item_pi(self) -> None:
        text = self._render("backlog-item", "pi")
        self.assertIn("Fresh Pi session", text)
        self.assertIn("`delegate` tool", text)
        self.assertIn("dev_status` tool", text)

    # -- make-skill -------------------------------------------------------

    def test_make_skill_claude(self) -> None:
        text = self._render("make-skill", "claude")
        self.assertIn("claude/commands/<name>.md", text)
        self.assertIn("ref/<skill>-<topic>.md", text)

    def test_make_skill_copilot(self) -> None:
        text = self._render("make-skill", "copilot")
        self.assertIn("copilot/skills/<name>/SKILL.md", text)
        self.assertIn("Copilot has no `AskUserQuestion`-style structured prompt", text)
        # Corrected, per copilot/CLAUDE_CODE_PARITY.md: typed-slash invocation
        # DOES exist -- the old hand-forked copy claimed it didn't.
        self.assertIn("explicit user-typed invocation", text)

    def test_make_skill_opencode(self) -> None:
        text = self._render("make-skill", "opencode")
        self.assertIn("opencode/skills/<name>/SKILL.md", text)
        self.assertNotIn("\nname:", text.split("---", 2)[1])

    def test_make_skill_agy(self) -> None:
        text = self._render("make-skill", "agy")
        self.assertIn("agy/skills/<skill>/references/<topic>.md", text)
        self.assertIn("agy has no `AskUserQuestion`-style structured prompt", text)
        # Corrected, per agy/CLAUDE_CODE_PARITY.md: slash invocation is
        # confirmed live as of agy 1.1.12 -- the old copy called it unconfirmed.
        self.assertIn("of agy 1.1.12", text)

    def test_make_skill_pi(self) -> None:
        text = self._render("make-skill", "pi")
        self.assertIn("pi/skills/<name>/SKILL.md", text)
        self.assertIn("references/<topic>.md", text)
        self.assertIn("/skill:<name>", text)

    # -- spec ---------------------------------------------------------------

    def test_spec_claude(self) -> None:
        text = self._render("spec", "claude")
        self.assertIn("argument-hint: [task description]", text)
        self.assertIn("AskUserQuestion", text)
        self.assertNotIn("the `question` tool", text)

    def test_spec_opencode(self) -> None:
        text = self._render("spec", "opencode")
        self.assertNotIn("\nname:", text.split("---", 2)[1])
        self.assertIn("the `question` tool", text)
        self.assertIn("spawn the `adversary` agent", text)

    def test_spec_pi(self) -> None:
        text = self._render("spec", "pi")
        self.assertNotIn("$ARGUMENTS", text)
        self.assertIn("the `question` tool", text)
        # The bug this item exists to fix: agy's copy claimed Pi has no
        # structured-choice widget and lacked this Pi-only note.
        self.assertNotIn("no built-in question/select tool", text)
        self.assertIn("rule out built-in sub-agents", text)

    # -- standup --------------------------------------------------------

    def test_standup_claude(self) -> None:
        text = self._render("standup", "claude")
        self.assertIn("Bash(python3 ~/.claude/scripts/standup.py:*)", text)
        self.assertIn("CLAUDE.md's pending-item status-transition rule", text)

    def test_standup_opencode(self) -> None:
        text = self._render("standup", "opencode")
        self.assertIn("python3 ~/.claude/scripts/dev_status.py pending update", text)
        self.assertIn("visible via `/dashboard`", text)

    def test_standup_pi(self) -> None:
        text = self._render("standup", "pi")
        self.assertIn("Call the `standup` tool with action `fetch`", text)
        self.assertIn("`dev_status` tool", text)

    # -- to-tickets -----------------------------------------------------

    def test_to_tickets_claude(self) -> None:
        text = self._render("to-tickets", "claude")
        self.assertIn("AskUserQuestion", text)
        self.assertIn("to_tickets_runner.py run", text)

    def test_to_tickets_opencode(self) -> None:
        text = self._render("to-tickets", "opencode")
        self.assertIn("`question` tool", text)
        self.assertIn("to_tickets_runner.py run", text)

    def test_to_tickets_pi(self) -> None:
        text = self._render("to-tickets", "pi")
        self.assertIn("`to_tickets` tool", text)
        self.assertNotIn("python3 ~/.claude/scripts/to_tickets_runner.py run", text)


class EndToEndTests(unittest.TestCase):
    """Assert the real templates + params render to exactly what's committed."""

    def test_all_29_copies_are_up_to_date(self) -> None:
        rendered = gs.render_all(REPO_ROOT, SKILL_PARAMS)
        self.assertEqual(len(rendered), 29)
        stale = []
        for relpath, text in rendered.items():
            on_disk = (REPO_ROOT / relpath).read_text(encoding="utf-8")
            if on_disk != text:
                stale.append(relpath)
        self.assertEqual(stale, [], f"stale (run gen_skills.py): {stale}")

    def test_every_output_path_has_the_marker(self) -> None:
        rendered = gs.render_all(REPO_ROOT, SKILL_PARAMS)
        for relpath, text in rendered.items():
            self.assertIn(
                "generated by claude/scripts/gen_skills.py",
                text,
                f"missing marker: {relpath}",
            )


if __name__ == "__main__":
    unittest.main()
